<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use Faker\Generator as Faker;
use App\Model\SelpIncidentModel;

$factory->define(SelpIncidentModel::class, function (Faker $faker) {
    return [
        'employee_name'=>$faker->name,
        'employee_cell'=>$faker->phoneNumber,
        'employee_designation'=>$faker->jobTitle,
        'employee_pin'=>$faker->randomDigitNot(0),
        'employee_selpzone_id'=>$faker->numberBetween(1,64),
        'employee_division_id'=>$faker->numberBetween(1,8),
        'employee_district_id'=>$faker->numberBetween(1,64),
        'employee_upazila_id'=>$faker->numberBetween(1,465),
        'information_provider_source_id'=>$faker->numberBetween(1,10),
        'type_of_dispute'=>$faker->numberBetween(1,2),
        'complain_against_gender_id'=>$faker->numberBetween(1,3),
        'selp_first_initiative_id'=>$faker->numberBetween(1,5),
        'survivor_name'=>$faker->name,
        'survivor_father_name'=>$faker->name,
        'survivor_mother_name'=>$faker->name,
        'survivor_husband_name'=>$faker->name,
        'survivor_1st_contact_no'=>$faker->phoneNumber,
        'survivor_2nd_contact_no'=>$faker->phoneNumber,
        'survivor_age'=>$faker->numberBetween(1,100),
        'survivor_sex_id'=>$faker->numberBetween(1,3),
        'survivor_education_id'=>$faker->numberBetween(1,5),
        'survivor_religion_id'=>$faker->numberBetween(1,5),
        'survivor_householdtype_id'=>$faker->numberBetween(1,5),
        'survivor_monthly_income'=>1000,
        'survivor_violence_location_id'=>$faker->numberBetween(1,5),
        'survivor_marital_status_id'=>$faker->numberBetween(1,3),
        'survivor_age_of_marriage'=>$faker->numberBetween(1,30),
        'survivor_organization_affiliation_id'=>$faker->numberBetween(1,5),
        'survivor_nid'=>$faker->creditCardNumber,
        'survivor_reason_of_violence_id'=>$faker->numberBetween(1,5),
        'survivor_place_of_violence_id'=>$faker->numberBetween(1,5),
        'survivor_disability_status_id'=>$faker->numberBetween(1,5),
        'number_of_perpetrator'=>$faker->numberBetween(1,5),
        'relation_with_main_perpetrator_id'=>$faker->numberBetween(1,10),
        'if_perpetrator_family_member_id'=>$faker->numberBetween(1,3),
        'perpetrator_gender_id'=>$faker->numberBetween(1,3),
        'perpetrator_age'=>$faker->numberBetween(1,100),
        'perpetrator_education_id'=>$faker->numberBetween(1,10),
        'perpetrator_occupation_id'=>$faker->numberBetween(1,10),
        'earlier_survivor_initiative'=>$faker->numberBetween(1,10),
        'earlier_survivor_initiative_place_id'=>$faker->numberBetween(1,10),
        'cause_of_failour_coming_to_selp_id'=>$faker->numberBetween(1,10),
        'selp_types_of_initiatives'=>$faker->numberBetween(1,10),
        'selp_referral_initiatives'=>$faker->numberBetween(1,10),
        'dispute_id'=>$faker->numberBetween(1000,10000),
        'selp_direct_support'=>$faker->numberBetween(1,10),
        'selp_alternative_dispute_resolution_id'=>$faker->numberBetween(1,10),
        'selp_support_start_date'=>date($format = 'Y-m-d'),
        'selp_support_closing_date'=>date($format = 'Y-m-d'),
        'selp_adrmoneyrecover_id'=>$faker->numberBetween(1,10),
        'selp_amount_of_money_from_adr'=>$faker->numberBetween(1,10000),
        'selp_adr_money_recover_benifitiaries'=>$faker->numberBetween(1,5),
        'case_type'=>$faker->numberBetween(1,5),
        'civilcase_id'=>$faker->numberBetween(1,5),
        'policecase_id'=>$faker->numberBetween(1,5),
        'pititioncase_id'=>$faker->numberBetween(1,5),
        'moneyrecover_id'=>$faker->numberBetween(1,5),
        'judgementstatus_id'=>$faker->numberBetween(1,5),
        'program_participent_followup'=>$faker->numberBetween(1,5),
        'no_of_followup_madeby_selp_staff'=>$faker->numberBetween(1,5),
        'followup_id'=>$faker->numberBetween(1,5),
        'case_start_date'=>date($format = 'Y-m-d'),
        'judgement_date'=>date($format = 'Y-m-d'),
        'have_survivor_face_violence_before'=>$faker->numberBetween(1,2),
        'survivor_first_violence_age'=>$faker->numberBetween(1,100),
        'violence_type_multiple_list'=>implode(array(1,2,3,4,5)),
        'survivor_seek_support_from_brac'=>$faker->numberBetween(1,5),
        'bracsupporttype_id'=>$faker->numberBetween(1,5)
    ];
});
